spring:
  datasource:
    url: jdbc:mysql://103.26.77.66:3306/ai_tools?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: cc7cd2086a482520